Bookers/config/routes.rb
Rails.application.routes.draw do

  root 'books#top'
  devise_for :users
  resources :users, only: [:show, :edit, :update, :index]
  get 'home/about' => 'books#about'
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Bookers/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Bookers/app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { in: 0..200 }

  def favorited?(user)
    # binding.pry
    favorites.where(user_id: user.id).exists?
  end
end

Bookers/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

Bookers/app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

Bookers/app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follow, class_name: "User"
  belongs_to :followed, class_name: "User"
end

Bookers/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :follew_relationships, class_name: "Relationship", foreign_key: "follew_id", dependent: :destroy
  has_many :follews, through: :follew_relationships, source: :follewed
  has_many :follewed_relationships, class_name: "Relationship", foreign_key: "follewed_id", dependent: :destroy
  has_many :follewed, through: :follewed_relationships, source: :follew

  validates :name, presence: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  attachment :profile_image
end

Bookers/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:top, :about]

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name, :email])
  end

end

Bookers/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def top
  end

  def about
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = 'You have creatad book successfully.'
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = current_user
      render "index"
    end
  end

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @comment = Comment.new
  end

  def edit
    @book = Book.find(params[:id])
    unless @book.user_id == current_user.id
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = 'You have updated book successfully.'
      redirect_to book_path
    else
      render "edit"
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

Bookers/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.book_id = @book.id
    @comment.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @comment = Comment.find_by(id: params[:id], book_id: params[:book_id])
    @comment.destroy
    redirect_back(fallback_location: root_path)
  end

  private
    def comment_params
      params.require(:comment).permit(:comment)
    end
end

Bookers/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    favorite = Favorite.new(book_id: @book.id)
    favorite.user_id = current_user.id
    favorite.save
    # redirect_back(fallback_location: root_path)
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = Favorite.find_by(book_id: params[:book_id])
    # favorite.user_id = current_user.id
    favorite.destroy
    # redirect_back(fallback_location: root_path)
  end
end

Bookers/app/controllers/posts_controller.rb
class PostsController < ApplicationController
end

Bookers/app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    follew = current_user.follew_relationships.new(follew_id: params[:user_id])
    follew.save
    redirect_bock(fallback_location: root_path)
  end

  def destroy
    fallew = current_user.follew_relationships.find_by(follew_id: params[:user_id])
    follew.destroy
    redirect_bock(fallback_location: root_path)
  end
end

Bookers/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @books = Book.all
    @book = Book.new
    @users = User.all
    @user = current_user
  end

  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = 'You have updated user successfully.'
      redirect_to user_path(@user.id)
    else
      render "edit"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

Bookers/app/helpers/application_helper.rb
module ApplicationHelper
end

Bookers/app/helpers/books_helper.rb
module BooksHelper
end

Bookers/app/helpers/comments_helper.rb
module CommentsHelper
end

Bookers/app/helpers/favorites_helper.rb
module FavoritesHelper
end

Bookers/app/helpers/posts_helper.rb
module PostsHelper
end

Bookers/app/helpers/relationships_helper.rb
module RelationshipsHelper
end

Bookers/app/helpers/users_helper.rb
module UsersHelper
end

Bookers/app/views/books/_list.html.erb
<!--サイドバー-->
<div class="col-xs-3">
  <section class="">
    <h2 class="">User info</h2>
    <div class="">
      <table class="">
        <td class="">
          <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
        </td>
        <tr class="">
          <td>name</td>
          <td><%= user.name %></td>
        </tr>
        <tr class="">
          <td>introduction</td>
          <td><%= user.introduction %></td>
        </tr>
        <tr class="">
          <td>
            <% if @user == current_user %>
              <%= link_to edit_user_path(user.id)  do %>
                <button type="button" class="btn btn-light"><span class="glyphicon glyphicon-wrench" aria-hidden="true"></span></button>
              <% end %>
            <% else %>
              <%= link_to user_path(current_user.id)  do %>
                <button type="button" class="btn btn-light"><span class="glyphicon glyphicon-wrench" aria-hidden="true"></span></button>
              <% end %>
            <% end %>
          </td>
        </tr>
      </table>
    </section>

    <section class="">
    <h2 class="">New book</h2>
    <div class="">
      <%= form_with model:book, local:true do |f| %>
        <% if book.errors.any? %>
          <p><%= book.errors.count %>errors prohibited this obj from being saved:</p>
          <ul>
          <% book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        <% end %>

        <h4>Title</h4>
        <%= f.text_field :title %>
        <h4>Opinion</h4>
        <%= f.text_area :body %>
        <div>
          <%= f.submit "Create Book" %>
        </div>
      <% end %>
    </div>
  </section>
</div>

Bookers/app/views/books/about.html.erb
<h1>welcome to <span class='glyphicon glyphicon-book'><strong>Bookers</strong>!</h1>

Bookers/app/views/books/edit.html.erb
<main>
  <div class="col-xs-9">
    <h2>Editing Book</h2>
    <div class="">
      <%= form_with model:@book, local:true do |f| %>
        <% if @book.errors.any? %>
          <%= @book.errors.count %>errors prohibited this obj from being saved:
          <% @book.errors.full_messages.each do |message| %>
            <%= message %>
          <% end %>
        <% end %>

        <h4>Title</h4>
        <%= f.text_field :title %>
        <h4>Opinion</h4>
        <%= f.text_area :body %>
        <div class="submit-button">
          <%= f.submit "Update Book" %>
        </div>
      <% end %>
      <div class="">
        <%= link_to "Show", book_path %>|<%= link_to "Back", books_path %>
      </div>
    </div>
  </div>
</main>

Bookers/app/views/books/index.html.erb
<main>
    <%= render 'books/list', book: @book, user: @user %>
    <div class="col-xs-9">
      <h2>Books</h2>
      <table class="table table-striped">
        <thead>
          <tr class="">
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book) do %>
                  <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg" %>
                <% end %>
              </td>
              <td class="">
                <%= link_to book_path(book) do %>
                  <i class=""></i><%= book.title %>
                <% end %>
              </td>
              <td>
                <%= book.body %>
              </td>
              <td>
                <div id="likes_buttons_<%= book.id %>">
                  <%= render 'favorites/favorite', book: book %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div id="back">
        <a href="#">
          <%= image_tag asset_path('arrow.png') %>
        </a>
      </div>
    </div>
</main>

Bookers/app/views/books/new.html.erb
<main>
  <h2>Users</h2>
  <div class="box">
    <table class="table-box">
      <tr class="title-box">
        <th>image</th>
        <th>name</th>
        <th></th>
      </tr>
      <% @users.each do |book| %>
        <tr class="contents">
          <td>
            <%= link_to book_path(book) do %>
              <%= attachment_image_tag @book.user, :profile_image %>
            <% end %>
          </td>
          <td>
            <%= book.name %>
          </td>
          <td class="link">
            <%= link_to book_path(book) do %>
              <i class="bt"></i><%= "Show" %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
  <!--サイドバー-->
  <div class="userinfo">
    <section class="popular">
      <h2 class="sidebar-heading">User info</h2>
      <div class="sidebar-contents">
        <table class="table-box">
          <td class="">
            <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg' %>
          </td>
          <tr class="title-box">
            <td>name</td>
            <td><%= @user.name %></td>
          </tr>
          <tr class="contents">
            <td>introduction</td>
            <td><%= @user.introduction %></td>
          </tr>
        </table>
      </div>
    </section>

    <section class="newbook">
      <h2 class="sidebar-heading">New book</h2>
      <div class="sidebar-contents">
        <%= form_with model:book, local:true do |f| %>
          <% if book.errors.any? %>
            <%= book.errors.count %>errors prohibited this obj from being saved:
            <% book.errors.full_messages.each do |message| %>
              <%= message %>
            <% end %>
          <% end %>

          <h4>Title</h4>
          <%= f.text_field :title %>
          <h4>Opinion</h4>
          <%= f.text_area :body %>
          <div class="submit-button">
            <%= f.submit "Create Book" %>
          </div>
        <% end %>
      </div>
    </section>
  </div>
</main>

Bookers/app/views/books/show.html.erb
<main>
  <%= render 'books/list', book: @book_new, user: @user %>
  <div class="col-xs-9">
    <h2>Book detail</h2>
    <table class="table table-striped">
      <tr class="">
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th></th>
        <th></th>
      </tr>
      <tr class="">
        <td>
          <%= link_to user_path(@user) do %>
            <%= attachment_image_tag @user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg" %><br>
            <%= @user.name %>
          <% end %>
        </td>
        <td class="">
          <%= link_to "#{@book.title}", book_path(@book.id) %>
        <td>
          <%= @book.body %>
        </td>
        <% if @book.user == current_user %>
          <td>
            <%= link_to "Edit", edit_book_path(@book), method: :get %>
          </td>
          <td>
            <%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "本当に消しますか？" %>
          </td>
        <% end %>
      </tr>
    </table>
    <div>
      <tr>
        <% @book.comments.each do |comment| %>
          <td>
            <%= attachment_image_tag(comment.user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg") %><br>
            <%= comment.user.name %>
          </td>
          <td>
            <%= comment.comment %>
          </td>
          <% if comment.user_id == current_user.id %>
            <td>
              <%= link_to "destroy", book_comment_path(comment.book_id, comment.id), method: :delete %>
            </td>
          <% end %>
        <% end %>
      </tr>
      <%= form_with(model:[@book, @comment], local: true) do |f| %>
        <%= f.text_area :comment %>
        <%= f.submit "送信" %>
      <% end %>
    </div>
  </div>
</main>

Bookers/app/views/books/top.html.erb
<body>
  <div class="col-xs-9 col-xs-offset-3">
    <h1>Welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span><strong>Bookers</strong>!!</h1>
    <p>In <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers,</p>
    <p>you can share and exchange your opinions , inpressions , and emotions<br>about various books!</p>
    <div class="">
      <div class="row">
        <%= link_to "Log in", new_user_session_path %>
      </div>
      <div class="row">
        <%= link_to "Sign up", new_user_registration_path %>
      </div>
    </div>
  </div>
</body>

Bookers/app/views/books/users_index.html.erb
<main>
  <%= render 'books/list', book: @book, user: @user %>
  <div class="col-lg-9">
    <h2>Users</h2>
    <table class="table table-striped">
      <tr class="title-box">
        <th>image</th>
        <th>name</th>
        <th></th>
      </tr>
      <% @users.each do |book| %>
        <tr class="contents">
          <td>
            <%= attachment_image_tag book, :profile_image, :fill, 50, 50, format: 'jpeg' %>
          </td>
          <td>
            <%= book.name %>
          </td>
          <td class="link">
            <%= link_to user_path(@user.id) do %>
              <i class="bt"></i><%= "Show" %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</main>

Bookers/app/views/favorites/_favorite.html.erb
<% if book.favorited?(current_user) %>
  <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
    <i class="glyphicon glyphicon-star" style="color: yellow;"></i>
    <!--<button id="btn">-->
    <!--  <i class="glyphicon glyphicon-star" style="color: yellow;"></i>-->
    <!--</button>-->
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book), method: :post, remote: true do %>
    <i class="glyphicon glyphicon-star"></i>
    <!--<button id="btn">-->
    <!--  <i class="glyphicon glyphicon-star"></i>-->
    <!--</button>-->
  <% end %>
<% end %>
<%= book.favorites.count %>いいね

Bookers/app/views/favorites/create.js.erb
$('#likes_buttons_<%= @book.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {book: @book}) %>");

Bookers/app/views/favorites/destroy.js.erb
$('#likes_buttons_<%= @book.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {book: @book}) %>");

Bookers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <!-- ヘッダー -->

  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <nav class="navbar-header">
        <span class="navbar-brand">Bookers</span>
      </nav>
      <nav class="">
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li class="">
              <%= link_to user_path(current_user.id) do %>
                <i class="glyphicon glyphicon-home" aria-hidden="true"> Home</i>
              <% end %>
            </li>
            <li class="">
              <%= link_to users_path do %>
                <i class="glyphicon glyphicon-user" aria-hidden="true"> Users</i>
              <% end %>
            </li>
            <li class="">
              <%= link_to books_path do %>
                <i class="glyphicon glyphicon-book" aria-hidden="true"> Books</i>
              <% end %>
            </li>
            <li class="">
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="glyphicon glyphicon-log-out" aria-hidden="true"> logout</i>
              <% end %>
            </li>
          <% else %>
            <li class="">
              <%= link_to root_path do %>
                <i class="glyphicon glyphicon-home" aria-hidden="true"> Home</i>
              <% end %>
            </li>
            <li class="">
              <%= link_to home_about_path do %>
                <i class="glyphicon glyphicon-link" aria-hidden="true"> About</i>
              <% end %>
            </li>
            <li class="">
              <%= link_to new_user_registration_path do %>
                <i class="glyphicon glyphicon-edit" aria-hidden="true"> sign up</i>
              <% end %>
            </li>
            <li class="">
              <%= link_to new_user_session_path do %>
                <i class="glyphicon glyphicon-log-in" aria-hidden="true"> login</i>
              <% end %>
            </li>
          <% end %>
        </ul>
      </nav>
    </div>
  </header>


  <body>
    <div class='container'>
      <div class='row'>
        <%= flash[:notice] %><!-- フラッシュメッセージ -->

        <%= yield %>
      </div>
    </div>
  </body>

  <!-- フッター -->
  <footer>
    <p class='col-xs-3 col-xs-offset-9'>
      CopyRight Infratop.inc
    </p>
  </footer>
</html>

Bookers/app/views/users/_list.html.erb
<!--サイドバー-->
<div class="col-xs-3">
  <div class="">
    <section class="">
      <h2 class="">User info</h2>
      <div class="">
        <table class="">
          <td class="">
            <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
          </td>
          <tr class="">
            <td>name</td>
            <td><%= user.name %></td>
          </tr>
          <tr class="">
            <td>introduction</td>
            <td><%= user.introduction %></td>
          </tr>
          <tr>
            <td>
              <% if @user == current_user %>
                <%= link_to edit_user_path(user.id)  do %>
                  <button type="button" class="btn btn-light"><span class="glyphicon glyphicon-wrench" aria-hidden="true"></span></button>
                <% end %>
              <% else %>
                <%= link_to user_path(current_user.id)  do %>
                  <button type="button" class="btn btn-light"><span class="glyphicon glyphicon-wrench" aria-hidden="true"></span></button>
                <% end %>
              <% end %>
            </td>
          </tr>
        </table>
      </div>
    </section>

    <section class="">
      <h2 class="">New book</h2>
      <div class="">
        <%= form_with model:@book, local:true do |f| %>
          <% if book.errors.any? %>
            <p><%= book.errors.count %>errors prohibited this obj from being saved:</p>
            <ul>
              <% book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          <% end %>

          <h4>Title</h4>
          <%= f.text_field :title %>
          <h4>Opinion</h4>
          <%= f.text_area :body %>
          <div class="">
            <%= f.submit "Create Book" %>
          </div>
        <% end %>
      </div>
    </section>
  </div>
</div>

Bookers/app/views/users/edit.html.erb
<section class="">
  <div class="container">
    <div class="">
      <h2 class="">User info</h2>
    </div>
    <div class="">
      <% if @user.errors.any? %>
        <p><%= @user.errors.count %>errors prohibited this obj from being saved:</p>
        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      <% end %>
      <%= form_with model:@user, local:true do |f| %>
        <div class="form-group has-icon">
          <label>Name</label>
          <%= f.text_field :name, autofocus: true %>
          <div class="form-group has-icon">
            <label>Image</label>
            <%= f.attachment_field :profile_image %>
          </div>
          <div class="form-group has-icon">Introduction</div>
          <%= f.text_field :introduction, autofocus: true %>
          <div>
          <%= f.submit "Update User" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

Bookers/app/views/users/index.html.erb
<main>
  <%= render 'users/list', book: @book, user: @user %>
  <div class="col-xs-9">

    <h2>Users</h2>
    <table class="table table-striped">
      <tr class="title-box">
        <th>image</th>
        <th>name</th>
        <th></th>
      </tr>
      <% @users.each do |book| %>
        <tr class="">
          <td>
            <%= attachment_image_tag book, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg" %>
          </td>
          <td>
            <%= book.name %>
          </td>
          <td class="link">
            <%= link_to user_path(book.id) do %>
              <i class="bt"></i><%= "Show" %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</main>

Bookers/app/views/users/show.html.erb
<main>
  <%= render 'users/list', book: @book, user: @user %>
  <div class="col-xs-9">
    <h2>Books</h2>
    <table class="table table-striped">
      <tr class="">
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
      </tr>
      <% @books.each do |book| %>
        <tr class="">
          <td>
            <%= attachment_image_tag @user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg" %>
          </td>
          <td class="">
            <%= link_to "#{book.title}", book_path(book.id) %>
          </td>
          <td>
            <%= book.body %>
          </td>
          <td>
            <link_to "フォローする", 

          </td>
        </tr>
      <% end %>
    </table>
  </div>
</main>